defaults:
  - callbacks: tabletennis
  - datamodule: tabletennis
  - model: mode_mp_agent_tabletennis
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog


root_data_dir: "/home/temp_store/weiran/table_tennis/"


clip_lang_model_name: ViT-B/32

log_dir: /home/temp_store/weiran/tt_logs
slurm: false
seed: 242
device: 'cuda'
batch_size: 16 # 38 # 128
devices: 1
#goal_window_size: 1
act_dim: 6
proprio_dims: 7
use_proprio: true
obs_dim: 512
goal_dim: 512
obs_seq_len: 1
act_seq_len: 120
multistep: ${act_seq_len}

max_epochs: 100
rollout_lh_skip_epochs: 30
num_workers: 1

trainer:
  devices: ${devices}
  precision: bf16
  max_epochs: ${max_epochs}
  sync_batchnorm: False
  accelerator: auto
  limit_train_batches: 1000
  limit_val_batches: 4
  # gradient_clip_val: 1

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  save_dir: .
  name: logger
  group: modemp_abs
  log_model: false
  project: table_tennis
  entity: mp_flow
  id: ???


hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - datamodule.root_data_dir
          - trainer.gpus
          - datamodule.num_workers
          - trainer.limit_train_batches
          - trainer.limit_val_batches